# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sailfish-polkit-agent

# >> macros
%define dbus_service_name org.sailfishos.polkit.daemon
%define dbus_service_path /org/sailfishos/polkit/daemon
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Sailfish polkit Agent
Version:    1.0.2
Release:    1
Group:      Qt/Qt
License:    LGPL
URL:        http://sailfishos.org/
Source0:    %{name}-%{version}.tar.bz2
Source100:  sailfish-polkit-agent.yaml
Requires:   dbus
Requires:   procps
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(polkit-qt-agent-1)
BuildRequires:  pkgconfig(polkit-qt-core-1)
BuildRequires:  pkgconfig(libsystemd-login)
BuildRequires:  pkgconfig(sailfishapp) >= 0.0.10

%description
This package contains the polkit authentication agent for Sailfish OS.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post

# Install agent into post-user-session
mkdir -p %{buildroot}%{_libdir}/systemd/user/post-user-session.target.wants
ln -s ../%{name}.service %{buildroot}%{_libdir}/systemd/user/post-user-session.target.wants/

# << install post

%preun
# >> preun

# Ask running daemon to quit
if pgrep -u root -f %{name} >/dev/null; then
dbus-send --system --dest=%{dbus_service_name} \
--print-reply %{dbus_service_path} \
%{dbus_service_name}.quit >/dev/null 2>&1 || true
fi
# Stop the agent
systemctl-user stop %{name}.service || :
systemctl-user daemon-reload || :

# << preun

%post
# >> post

# Ask running daemon to quit
if pgrep -u root -f %{name} >/dev/null; then
dbus-send --system --dest=%{dbus_service_name} \
--print-reply %{dbus_service_path} \
%{dbus_service_name}.quit >/dev/null 2>&1 || true
fi
# (Re-)start the agent
systemctl-user daemon-reload || :
systemctl-user stop %{name}.service || :
systemctl-user start %{name}.service || :

# << post

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/%{name}/qml/*.qml
%{_libexecdir}/sailfish-polkit-daemon
%{_datadir}/dbus-1/system-services/%{dbus_service_name}.service
%{_sysconfdir}/dbus-1/system.d/%{dbus_service_name}.conf
%{_libdir}/systemd/user/%{name}.service
%{_libdir}/systemd/user/post-user-session.target.wants/%{name}.service
# >> files
# << files
